### ISSUE TITLE
Project Specification

### ISSUE THREAD

**Issue by tiagomenegaz** [tmmgarcia/ruby-rake-cron#1]
Tasks

- [x] add .gitignore #2
- [x] add ruby gem configuration #3
- [x] add whenever gem #3
- [x] add configurated dockerfile #4
- [x] push it to DockerHub
- [x] update readme #5 
- [ ] improve logging using log file
